# 该文档用于翻译warframe market物品
# 文档包括：战甲类、武器类、MOD类、附能类、紫卡类、物品类
# <查询字符>:<wm关键字>
# 文档末尾为翻译函数
# "":"",

# 翻译字典
def dictionary():
	data={
		# 战甲类
		"ASH PRIME":"ash_prime_set",
		"ASH PRIME 头部神经光元":"ash_prime_neuroptics",
		"ASH PRIME 系统":"ash_prime_systems",
		"ASH PRIME 机体":"ash_prime_chassis",
		"ASH PRIME 蓝图":"ash_prime_blueprint",
		"ASH P":"ash_prime_set",
		"ASH P头":"ash_prime_neuroptics",
		"ASH P系统":"ash_prime_systems",
		"ASH P机体":"ash_prime_chassis",
		"ASH P蓝图":"ash_prime_blueprint",

		"MAG PRIME":"mag_prime_set",
		"MAG PRIME 头部神经光元":"mag_prime_neuroptics",
		"MAG PRIME 系统":"mag_prime_systems",
		"MAG PRIME 蓝图":"mag_prime_blueprint",
		"MAG PRIME 机体":"mag_prime_chassis",
		"MAG P":"mag_prime_set",
		"MAG P头":"mag_prime_neuroptics",
		"MAG P系统":"mag_prime_systems",
		"MAG P蓝图":"mag_prime_blueprint",
		"MAG P机体":"mag_prime_chassis",
		"磁妹P":"mag_prime_set",
		"磁妹P头":"mag_prime_neuroptics",
		"磁妹P系统":"mag_prime_systems",
		"磁妹P蓝图":"mag_prime_blueprint",
		"磁妹P机体":"mag_prime_chassis",

		"MIRAGE PRIME":"mirage_prime_set",
		"MIRAGE PRIME 头部神经光元":"mirage_prime_neuroptics",
		"MIRAGE PRIME 系统":"mirage_prime_systems",
		"MIRAGE PRIME 机体":"mirage_prime_chassis",
		"MIRAGE PRIME 蓝图":"mirage_prime_blueprint",
		"MIRAGE P":"mirage_prime_set",
		"MIRAGE P头":"mirage_prime_neuroptics",
		"MIRAGE P系统":"mirage_prime_systems",
		"MIRAGE P机体":"mirage_prime_chassis",
		"MIRAGE P蓝图":"mirage_prime_blueprint",
		"小丑P":"mirage_prime_set",
		"小丑P头":"mirage_prime_neuroptics",
		"小丑P系统":"mirage_prime_systems",
		"小丑P机体":"mirage_prime_chassis",
		"小丑P蓝图":"mirage_prime_blueprint",

		"NEKROS PRIME":"nekros_prime_set",
		"NEKROS PRIME 头部神经光元":"nekros_prime_neuroptics",
		"NEKROS PRIME 系统":"nekros_prime_systems",
		"NEKROS PRIME 机体":"nekros_prime_chassis",
		"NEKROS PRIME 蓝图":"nekros_prime_blueprint",
		"NEKROS P":"nekros_prime_set",
		"NEKROS P头":"nekros_prime_neuroptics",
		"NEKROS P系统":"nekros_prime_systems",
		"NEKROS P机体":"nekros_prime_chassis",
		"NEKROS P蓝图":"nekros_prime_blueprint",
		"摸尸P":"nekros_prime_set",
		"摸尸P头":"nekros_prime_neuroptics",
		"摸尸P系统":"nekros_prime_systems",
		"摸尸P机体":"nekros_prime_chassis",
		"摸尸P蓝图":"nekros_prime_blueprint",

		"LIMBO PRIME":"limbo_prime_set",
		"LIMBO PRIME 头部神经光元":"limbo_prime_neuroptics",
		"LIMBO PRIME 系统":"limbo_prime_systems",
		"LIMBO PRIME 蓝图":"limbo_prime_blueprint",
		"LIMBO PRIME 机体":"limbo_prime_chassis",
		"LIMBO P":"limbo_prime_set",
		"LIMBO P头":"limbo_prime_neuroptics",
		"LIMBO P系统":"limbo_prime_systems",
		"LIMBO P蓝图":"limbo_prime_blueprint",
		"LIMBO P机体":"limbo_prime_chassis",
		"小明P":"limbo_prime_set",
		"小明P头":"limbo_prime_neuroptics",
		"小明P系统":"limbo_prime_systems",
		"小明P蓝图":"limbo_prime_blueprint",
		"小明P机体":"limbo_prime_chassis",

		"NOVA PRIME":"nova_prime_set",
		"NOVA PRIME 头部神经光元":"nova_prime_neuroptics",
		"NOVA PRIME 系统":"nova_prime_systems",
		"NOVA PRIME 机体":"nova_prime_chassis",
		"NOVA PRIME 蓝图":"nova_prime_blueprint",
		"NOVA P":"nova_prime_set",
		"NOVA P头":"nova_prime_neuroptics",
		"NOVA P系统":"nova_prime_systems",
		"NOVA P机体":"nova_prime_chassis",
		"NOVA P蓝图":"nova_prime_blueprint",

		"OBERON PRIME":"oberon_prime_set",
		"OBERON PRIME 头部神经光元":"oberon_prime_neuroptics",
		"OBERON PRIME 系统":"oberon_prime_systems",
		"OBERON PRIME 机体":"oberon_prime_chassis",
		"OBERON PRIME 蓝图":"oberon_prime_blueprint",
		"OBERON P":"oberon_prime_set",
		"OBERON P头":"oberon_prime_neuroptics",
		"OBERON P系统":"oberon_prime_systems",
		"OBERON P机体":"oberon_prime_chassis",
		"OBERON P蓝图":"oberon_prime_blueprint",
		"奶爸P":"oberon_prime_set",
		"奶爸P头":"oberon_prime_neuroptics",
		"奶爸P系统":"oberon_prime_systems",
		"奶爸P机体":"oberon_prime_chassis",
		"奶爸P蓝图":"oberon_prime_blueprint",

		"ZEPHYR PRIME":"zephyr_prime_set",
		"ZEPHYR PRIME 头部神经光元":"zephyr_prime_neuroptics",
		"ZEPHYR PRIME 蓝图":"zephyr_prime_blueprint",
		"ZEPHYR PRIME 机体":"zephyr_prime_chassis",
		"ZEPHYR PRIME 系统":"zephyr_prime_systems",
		"ZEPHYR P":"zephyr_prime_set",
		"ZEPHYR P头":"zephyr_prime_neuroptics",
		"ZEPHYR P蓝图":"zephyr_prime_blueprint",
		"ZEPHYR P机体":"zephyr_prime_chassis",
		"ZEPHYR P系统":"zephyr_prime_systems",
		"鸟姐P":"zephyr_prime_set",
		"鸟姐P头":"zephyr_prime_neuroptics",
		"鸟姐P蓝图":"zephyr_prime_blueprint",
		"鸟姐P机体":"zephyr_prime_chassis",
		"鸟姐P系统":"zephyr_prime_systems",
		

		"NYX PRIME":"nyx_prime_set",
		"NYX PRIME 头部神经光元":"nyx_prime_neuroptics",
		"NYX PRIME 系统":"nyx_prime_systems",
		"NYX PRIME 机体":"nyx_prime_chassis",
		"NYX PRIME 蓝图":"nyx_prime_blueprint",
		"NYX P":"nyx_prime_set",
		"NYX P头":"nyx_prime_neuroptics",
		"NYX P系统":"nyx_prime_systems",
		"NYX P机体":"nyx_prime_chassis",
		"NYX P蓝图":"nyx_prime_blueprint",

		"LOKI PRIME":"loki_prime_set",
		"LOKI PRIME 头部神经光元":"loki_prime_neuroptics",
		"LOKI PRIME 系统":"loki_prime_systems",
		"LOKI PRIME 机体":"loki_prime_chassis",
		"LOKI PRIME 蓝图":"loki_prime_blueprint",
		"LOKI P":"loki_prime_set",
		"LOKI P头":"loki_prime_neuroptics",
		"LOKI P系统":"loki_prime_systems",
		"LOKI P机体":"loki_prime_chassis",
		"LOKI P蓝图":"loki_prime_blueprint",

		"RHINO PRIME":"rhino_prime_set",
		"RHINO PRIME 头部神经光元":"rhino_prime_neuroptics",
		"RHINO PRIME 系统":"rhino_prime_systems",
		"RHINO PRIME 机体":"rhino_prime_chassis",
		"RHINO PRIME 蓝图":"rhino_prime_blueprint",
		"RHINO P":"rhino_prime_set",
		"RHINO P头":"rhino_prime_neuroptics",
		"RHINO P系统":"rhino_prime_systems",
		"RHINO P机体":"rhino_prime_chassis",
		"RHINO P蓝图":"rhino_prime_blueprint",
		"牛P":"rhino_prime_set",
		"牛P头":"rhino_prime_neuroptics",
		"牛P系统":"rhino_prime_systems",
		"牛P机体":"rhino_prime_chassis",
		"牛P蓝图":"rhino_prime_blueprint",

		"TRINITY PRIME":"trinity_prime_set",
		"TRINITY PRIME 系统":"trinity_prime_systems",
		"TRINITY PRIME 机体":"trinity_prime_chassis",
		"TRINITY PRIME 蓝图":"trinity_prime_blueprint",
		"TRINITY PRIME 头部神经光元":"trinity_prime_neuroptics",
		"TRINITY P":"trinity_prime_set",
		"TRINITY P系统":"trinity_prime_systems",
		"TRINITY P机体":"trinity_prime_chassis",
		"TRINITY P蓝图":"trinity_prime_blueprint",
		"TRINITY P头":"trinity_prime_neuroptics",
		"奶妈P":"trinity_prime_set",
		"奶妈P系统":"trinity_prime_systems",
		"奶妈P机体":"trinity_prime_chassis",
		"奶妈P蓝图":"trinity_prime_blueprint",
		"奶妈P头":"trinity_prime_neuroptics",

		"VALKYR PRIME":"valkyr_prime_set",
		"VALKYR PRIME 头部神经光元":"valkyr_prime_neuroptics",
		"VALKYR PRIME 系统":"valkyr_prime_systems",
		"VALKYR PRIME 机体":"valkyr_prime_chassis",
		"VALKYR PRIME 蓝图":"valkyr_prime_blueprint",
		"VALKYR P":"valkyr_prime_set",
		"VALKYR P头":"valkyr_prime_neuroptics",
		"VALKYR P系统":"valkyr_prime_systems",
		"VALKYR P机体":"valkyr_prime_chassis",
		"VALKYR P蓝图":"valkyr_prime_blueprint",
		"女汉子P":"valkyr_prime_set",
		"女汉子P头":"valkyr_prime_neuroptics",
		"女汉子P系统":"valkyr_prime_systems",
		"女汉子P机体":"valkyr_prime_chassis",
		"女汉子P蓝图":"valkyr_prime_blueprint",

		"VAUBAN PRIME":"vauban_prime_set",
		"VAUBAN PRIME 系统":"vauban_prime_systems",
		"VAUBAN PRIME 机体":"vauban_prime_chassis",
		"VAUBAN PRIME 蓝图":"vauban_prime_blueprint",
		"VAUBAN PRIME 头部神经光元":"vauban_prime_neuroptics",
		"VAUBAN P":"vauban_prime_set",
		"VAUBAN P系统":"vauban_prime_systems",
		"VAUBAN P机体":"vauban_prime_chassis",
		"VAUBAN P蓝图":"vauban_prime_blueprint",
		"VAUBAN P头":"vauban_prime_neuroptics",
		"工程P":"vauban_prime_set",
		"工程P系统":"vauban_prime_systems",
		"工程P机体":"vauban_prime_chassis",
		"工程P蓝图":"vauban_prime_blueprint",
		"工程P头":"vauban_prime_neuroptics",

		"INAROS PRIME":"inaros_prime_set",
		"INAROS PRIME 机体":"inaros_prime_chassis",
		"INAROS PRIME 系统":"inaros_prime_systems",
		"INAROS PRIME 蓝图":"inaros_prime_blueprint",
		"INAROS PRIME 头部神经光元":"inaros_prime_neuroptics",
		"INAROS P":"inaros_prime_set",
		"INAROS P机体":"inaros_prime_chassis",
		"INAROS P系统":"inaros_prime_systems",
		"INAROS P蓝图":"inaros_prime_blueprint",
		"INAROS P头":"inaros_prime_neuroptics",
		"沙甲P":"inaros_prime_set",
		"沙甲P机体":"inaros_prime_chassis",
		"沙甲P系统":"inaros_prime_systems",
		"沙甲P蓝图":"inaros_prime_blueprint",
		"沙甲P头":"inaros_prime_neuroptics",

		"VOLT PRIME":"volt_prime_set",
		"VOLT PRIME 蓝图":"volt_prime_blueprint",
		"VOLT PRIME 头部神经光元":"volt_prime_neuroptics",
		"VOLT PRIME 系统":"volt_prime_systems",
		"VOLT PRIME 机体":"volt_prime_chassis",
		"VOLT P":"volt_prime_set",
		"VOLT P蓝图":"volt_prime_blueprint",
		"VOLT P头":"volt_prime_neuroptics",
		"VOLT P系统":"volt_prime_systems",
		"VOLT P机体":"volt_prime_chassis",
		"电男P":"volt_prime_set",
		"电男P蓝图":"volt_prime_blueprint",
		"电男P头":"volt_prime_neuroptics",
		"电男P系统":"volt_prime_systems",
		"电男P机体":"volt_prime_chassis",

		"SARYN PRIME":"saryn_prime_set",
		"SARYN PRIME 蓝图":"saryn_prime_blueprint",
		"SARYN PRIME 机体":"saryn_prime_chassis",
		"SARYN PRIME 系统":"saryn_prime_systems",
		"SARYN PRIME 头部神经光元":"saryn_prime_neuroptics",
		"SARYN P":"saryn_prime_set",
		"SARYN P蓝图":"saryn_prime_blueprint",
		"SARYN P机体":"saryn_prime_chassis",
		"SARYN P系统":"saryn_prime_systems",
		"SARYN P头":"saryn_prime_neuroptics",
		"毒妈P":"saryn_prime_set",
		"毒妈P蓝图":"saryn_prime_blueprint",
		"毒妈P机体":"saryn_prime_chassis",
		"毒妈P系统":"saryn_prime_systems",
		"毒妈P头":"saryn_prime_neuroptics",

		"HYDROID PRIME":"hydroid_prime_set",
		"HYDROID PRIME 蓝图":"hydroid_prime_blueprint",
		"HYDROID PRIME 机体":"hydroid_prime_chassis",
		"HYDROID PRIME 系统":"hydroid_prime_systems",
		"HYDROID PRIME 头部神经光元":"hydroid_prime_neuroptics",
		"HYDROID P":"hydroid_prime_set",
		"HYDROID P蓝图":"hydroid_prime_blueprint",
		"HYDROID P机体":"hydroid_prime_chassis",
		"HYDROID P系统":"hydroid_prime_systems",
		"HYDROID P头":"hydroid_prime_neuroptics",
		"水男P":"hydroid_prime_set",
		"水男P蓝图":"hydroid_prime_blueprint",
		"水男P机体":"hydroid_prime_chassis",
		"水男P系统":"hydroid_prime_systems",
		"水男P头":"hydroid_prime_neuroptics",

		"FROST PRIME":"frost_prime_set",
		"FROST PRIME 头部神经光元":"frost_prime_neuroptics",
		"FROST PRIME 系统":"frost_prime_systems",
		"FROST PRIME 机体":"frost_prime_chassis",
		"FROST PRIME 蓝图":"frost_prime_blueprint",
		"FROST P":"frost_prime_set",
		"FROST P头":"frost_prime_neuroptics",
		"FROST P系统":"frost_prime_systems",
		"FROST P机体":"frost_prime_chassis",
		"FROST P蓝图":"frost_prime_blueprint",
		"冰男P":"frost_prime_set",
		"冰男P头":"frost_prime_neuroptics",
		"冰男P系统":"frost_prime_systems",
		"冰男P机体":"frost_prime_chassis",
		"冰男P蓝图":"frost_prime_blueprint",

		"TITANIA PRIME":"titania_prime_set",
		"TITANIA PRIME 头部神经光元":"titania_prime_neuroptics",
		"TITANIA PRIME 机体":"titania_prime_chassis",
		"TITANIA PRIME 系统":"titania_prime_systems",
		"TITANIA PRIME 蓝图":"titania_prime_blueprint",
		"TITANIA P":"titania_prime_set",
		"TITANIA P头":"titania_prime_neuroptics",
		"TITANIA P机体":"titania_prime_chassis",
		"TITANIA P系统":"titania_prime_systems",
		"TITANIA P蓝图":"titania_prime_blueprint",
		"蝴蝶甲P":"titania_prime_set",
		"蝴蝶甲P头":"titania_prime_neuroptics",
		"蝴蝶甲P机体":"titania_prime_chassis",
		"蝴蝶甲P系统":"titania_prime_systems",
		"蝴蝶甲P蓝图":"titania_prime_blueprint",

		"EMBER PRIME":"ember_prime_set",
		"EMBER PRIME 头部神经光元":"ember_prime_neuroptics",
		"EMBER PRIME 系统":"ember_prime_systems",
		"EMBER PRIME 机体":"ember_prime_chassis",
		"EMBER PRIME 蓝图":"ember_prime_blueprint",
		"EMBER P":"ember_prime_set",
		"EMBER P头":"ember_prime_neuroptics",
		"EMBER P系统":"ember_prime_systems",
		"EMBER P机体":"ember_prime_chassis",
		"EMBER P蓝图":"ember_prime_blueprint",
		"火鸡P":"ember_prime_set",
		"火鸡P头":"ember_prime_neuroptics",
		"火鸡P系统":"ember_prime_systems",
		"火鸡P机体":"ember_prime_chassis",
		"火鸡P蓝图":"ember_prime_blueprint",

		"BANSHEE PRIME":"banshee_prime_set",
		"BANSHEE PRIME 头部神经光元":"banshee_prime_neuroptics",
		"BANSHEE PRIME 系统":"banshee_prime_systems",
		"BANSHEE PRIME 机体":"banshee_prime_chassis",
		"BANSHEE PRIME 蓝图":"banshee_prime_blueprint",
		"BANSHEE P":"banshee_prime_set",
		"BANSHEE P头":"banshee_prime_neuroptics",
		"BANSHEE P系统":"banshee_prime_systems",
		"BANSHEE P机体":"banshee_prime_chassis",
		"BANSHEE P蓝图":"banshee_prime_blueprint",
		"音妈P":"banshee_prime_set",
		"音妈P头":"banshee_prime_neuroptics",
		"音妈P系统":"banshee_prime_systems",
		"音妈P机体":"banshee_prime_chassis",
		"音妈P蓝图":"banshee_prime_blueprint",

		"WUKONG PRIME":"wukong_prime_set",
		"WUKONG PRIME 蓝图":"wukong_prime_blueprint",
		"WUKONG PRIME 头部神经光元":"wukong_prime_neuroptics",
		"WUKONG PRIME 机体":"wukong_prime_chassis",
		"WUKONG PRIME 系统":"wukong_prime_systems",
		"WUKONG P":"wukong_prime_set",
		"WUKONG P蓝图":"wukong_prime_blueprint",
		"WUKONG P头":"wukong_prime_neuroptics",
		"WUKONG P机体":"wukong_prime_chassis",
		"WUKONG P系统":"wukong_prime_systems",
		"悟空P":"wukong_prime_set",
		"悟空P蓝图":"wukong_prime_blueprint",
		"悟空P头":"wukong_prime_neuroptics",
		"悟空P机体":"wukong_prime_chassis",
		"悟空P系统":"wukong_prime_systems",

		"MESA PRIME":"mesa_prime_set",
		"MESA PRIME 系统":"mesa_prime_systems",
		"MESA PRIME 机体":"mesa_prime_chassis",
		"MESA PRIME 蓝图":"mesa_prime_blueprint",
		"MESA PRIME 头部神经光元":"mesa_prime_neuroptics",
		"MESA P":"mesa_prime_set",
		"MESA P系统":"mesa_prime_systems",
		"MESA P机体":"mesa_prime_chassis",
		"MESA P蓝图":"mesa_prime_blueprint",
		"MESA P头":"mesa_prime_neuroptics",
		"女枪P":"mesa_prime_set",
		"女枪P系统":"mesa_prime_systems",
		"女枪P机体":"mesa_prime_chassis",
		"女枪P蓝图":"mesa_prime_blueprint",
		"女枪P头":"mesa_prime_neuroptics",

		"CHROMA PRIME":"chroma_prime_set",
		"CHROMA PRIME 蓝图":"chroma_prime_blueprint",
		"CHROMA PRIME 系统":"chroma_prime_systems",
		"CHROMA PRIME 头部神经光元":"chroma_prime_neuroptics",
		"CHROMA PRIME 机体":"chroma_prime_chassis",
		"CHROMA P":"chroma_prime_set",
		"CHROMA P蓝图":"chroma_prime_blueprint",
		"CHROMA P系统":"chroma_prime_systems",
		"CHROMA P头":"chroma_prime_neuroptics",
		"CHROMA P机体":"chroma_prime_chassis",
		"龙甲P":"chroma_prime_set",
		"龙甲P蓝图":"chroma_prime_blueprint",
		"龙甲P系统":"chroma_prime_systems",
		"龙甲P头":"chroma_prime_neuroptics",
		"龙甲P机体":"chroma_prime_chassis",

		"EQUINOX PRIME":"equinox_prime_set",
		"EQUINOX PRIME 头部神经光元":"equinox_prime_neuroptics",
		"EQUINOX PRIME 系统":"equinox_prime_systems",
		"EQUINOX PRIME 机体":"equinox_prime_chassis",
		"EQUINOX PRIME 蓝图":"equinox_prime_blueprint",
		"EQUINOX P":"equinox_prime_set",
		"EQUINOX P头":"equinox_prime_neuroptics",
		"EQUINOX P系统":"equinox_prime_systems",
		"EQUINOX P机体":"equinox_prime_chassis",
		"EQUINOX P蓝图":"equinox_prime_blueprint",
		"阴阳P":"equinox_prime_set",
		"阴阳P头":"equinox_prime_neuroptics",
		"阴阳P系统":"equinox_prime_systems",
		"阴阳P机体":"equinox_prime_chassis",
		"阴阳P蓝图":"equinox_prime_blueprint",

		"ATLAS PRIME":"atlas_prime_set",
		"ATLAS PRIME 系统":"atlas_prime_systems",
		"ATLAS PRIME 蓝图":"atlas_prime_blueprint",
		"ATLAS PRIME 机体":"atlas_prime_chassis",
		"ATLAS PRIME 头部神经光元":"atlas_prime_neuroptics",
		"ATLAS P":"atlas_prime_set",
		"ATLAS P系统":"atlas_prime_systems",
		"ATLAS P蓝图":"atlas_prime_blueprint",
		"ATLAS P机体":"atlas_prime_chassis",
		"ATLAS P头":"atlas_prime_neuroptics",
		"土甲P":"atlas_prime_set",
		"土甲P系统":"atlas_prime_systems",
		"土甲P蓝图":"atlas_prime_blueprint",
		"土甲P机体":"atlas_prime_chassis",
		"土甲P头":"atlas_prime_neuroptics",
		
		"IVARA PRIME":"ivara_prime_set",
		"IVARA PRIME 头部神经光元":"ivara_prime_neuroptics",
		"IVARA PRIME 机体":"ivara_prime_chassis",
		"IVARA PRIME 系统":"ivara_prime_systems",
		"IVARA PRIME 蓝图":"ivara_prime_blueprint",
		"IVARA P":"ivara_prime_set",
		"IVARA P头":"ivara_prime_neuroptics",
		"IVARA P机体":"ivara_prime_chassis",
		"IVARA P系统":"ivara_prime_systems",
		"IVARA P蓝图":"ivara_prime_blueprint",
		"弓妹P":"ivara_prime_set",
		"弓妹P头":"ivara_prime_neuroptics",
		"弓妹P机体":"ivara_prime_chassis",
		"弓妹P系统":"ivara_prime_systems",
		"弓妹P蓝图":"ivara_prime_blueprint",

		# 武器类
		"恶狼战锤":"wolf_sledge_set",
		"恶狼战锤蓝图":"wolf_sledge_blueprint",
		"恶狼战锤握柄":"wolf_sledge_handle",
		"恶狼战锤锤头":"wolf_sledge_head",
		"恶狼战锤马达":"wolf_sledge_motor",

		"苍鹰P":"baza_prime_set",
		"苍鹰P枪管":"baza_prime_barrel",
		"苍鹰P枪托":"baza_prime_stock",
		"苍鹰P枪机":"baza_prime_receiver",
		"苍鹰P蓝图":"baza_prime_blueprint",

		"轻灵月神双枪P":"aksomati_prime_set",
		"轻灵月神双枪P连接器":"aksomati_prime_link",
		"轻灵月神双枪P枪机":"aksomati_prime_receiver",
		"轻灵月神双枪P蓝图":"aksomati_prime_blueprint",
		"轻灵月神双枪P枪管":"aksomati_prime_barrel",
		
		"死亡魔方P":"dethcube_prime_set",
		"死亡魔方P外壳":"dethcube_prime_carapace",
		"死亡魔方P头部":"dethcube_prime_cerebrum",
		"死亡魔方P蓝图":"dethcube_prime_blueprint",
		"死亡魔方P系统":"dethcube_prime_systems",

		"铁钩手甲P":"tekko_prime_set",
		"铁钩手甲P蓝图":"tekko_prime_blueprint",
		"铁钩手甲P拳套":"tekko_prime_gauntlet",
		"铁钩手甲P刀刃":"tekko_prime_blade",

		"救赎者P":"redeemer_prime_set",
		"救赎者P蓝图":"redeemer_prime_blueprint",
		"救赎者P刀刃":"redeemer_prime_blade",
		"救赎者P握柄":"redeemer_prime_handle",

		"斯特拉迪瓦P":"stradavar_prime_set",
		"斯特拉迪瓦P枪管":"stradavar_prime_barrel",
		"斯特拉迪瓦P枪机":"stradavar_prime_receiver",
		"斯特拉迪瓦P枪托":"stradavar_prime_stock",
		"斯特拉迪瓦P蓝图":"stradavar_prime_blueprint",

		"降灵追猎者P握柄":"ninkondi_prime_handle",
		"降灵追猎者P":"ninkondi_prime_set",
		"降灵追猎者P链条":"ninkondi_prime_chain",
		"降灵追猎者P蓝图":"ninkondi_prime_blueprint",

		"狂鲨P":"tiberon_prime_set",
		"狂鲨P枪机":"tiberon_prime_receiver",
		"狂鲨P蓝图":"tiberon_prime_blueprint",
		"狂鲨P枪管":"tiberon_prime_barrel",
		"狂鲨P枪托":"tiberon_prime_stock",

		"觉醒双枪P":"akjagara_prime_set",
		"觉醒双枪P蓝图":"akjagara_prime_blueprint",
		"觉醒双枪P枪机":"akjagara_prime_receiver",
		"觉醒双枪P连接器":"akjagara_prime_link",
		"觉醒双枪P枪管":"akjagara_prime_barrel",

		"皇家拐刃P":"kronen_prime_set",
		"皇家拐刃P刀刃":"kronen_prime_blade",
		"皇家拐刃P握柄":"kronen_prime_handle",
		"皇家拐刃P蓝图":"kronen_prime_blueprint",

		"格拉姆P":"gram_prime_set",
		"格拉姆P蓝图":"gram_prime_blueprint",
		"格拉姆P刀刃":"gram_prime_blade",
		"格拉姆P握柄":"gram_prime_handle",

		"席瓦&神盾P":"silva_and_aegis_prime_set",
		"席瓦&神盾P蓝图":"silva_and_aegis_prime_blueprint",
		"席瓦&神盾P刀刃":"silva_and_aegis_prime_blade",
		"席瓦&神盾P护手":"silva_and_aegis_prime_guard",
		"席瓦&神盾P握柄":"silva_and_aegis_prime_hilt",

		"拉斯波恩":"rathbone_set",
		"拉斯波恩锤头":"rathbone_head",
		"拉斯波恩握柄":"rathbone_handle",

		"战刃P":"glaive_prime_set",
		"战刃P蓝图":"glaive_prime_blueprint",
		"战刃P刀刃":"glaive_prime_blade",
		"战刃P圆盘":"glaive_prime_disc",

		"欧特鲁斯P":"orthos_prime_set",
		"欧特鲁斯P蓝图":"orthos_prime_blueprint",
		"欧特鲁斯P刀刃":"orthos_prime_blade",
		"欧特鲁斯P握柄":"orthos_prime_handle",

		"史提托双枪P":"akstiletto_prime_set",
		"史提托双枪P蓝图":"akstiletto_prime_blueprint",
		"史提托双枪P枪管":"akstiletto_prime_barrel",
		"史提托双枪P枪机":"akstiletto_prime_receiver",
		"史提托双枪P连接器":"akstiletto_prime_link",

		"布里斯提卡P":"ballistica_prime_set",
		"布里斯提卡P蓝图":"ballistica_prime_blueprint",
		"布里斯提卡P上弓臂":"ballistica_prime_upper_limb",
		"布里斯提卡P下弓臂":"ballistica_prime_lower_limb",
		"布里斯提卡P枪机":"ballistica_prime_receiver",
		"布里斯提卡P弓弦":"ballistica_prime_string",

		"悦音P":"euphona_prime_set",
		"悦音P蓝图":"euphona_prime_blueprint",
		"悦音P枪管":"euphona_prime_barrel",
		"悦音P枪机":"euphona_prime_receiver",

		"旋刃飞刀P":"spira_prime_set",
		"旋刃飞刀P蓝图":"spira_prime_blueprint",
		"旋刃飞刀P刀刃":"spira_prime_blade",
		"旋刃飞刀P镖袋":"spira_prime_pouch",

		"暗杀者P":"sicarus_prime_set",
		"暗杀者P枪机":"sicarus_prime_receiver",
		"暗杀者P枪管":"sicarus_prime_barrel",
		"暗杀者P蓝图":"sicarus_prime_blueprint",

		"瓦斯托P":"vasto_prime_set",
		"瓦斯托P枪机":"vasto_prime_receiver",
		"瓦斯托P蓝图":"vasto_prime_blueprint",
		"瓦斯托P枪管":"vasto_prime_barrel",

		"野猪P":"boar_prime_set",
		"野猪P蓝图":"boar_prime_blueprint",
		"野猪P枪机":"boar_prime_receiver",
		"野猪P枪管":"boar_prime_barrel",
		"野猪P枪托":"boar_prime_stock",

		"螺钉双枪P":"akbolto_prime_set",
		"螺钉双枪P蓝图":"akbolto_prime_blueprint",
		"螺钉双枪P枪管":"akbolto_prime_barrel",
		"螺钉双枪P枪机":"akbolto_prime_receiver",
		"螺钉双枪P连接器":"akbolto_prime_link",

		"野马双枪P":"akbronco_prime_set",
		"野马双枪P连接器":"akbronco_prime_link",
		"野马双枪P蓝图":"akbronco_prime_blueprint",

		"雷克斯P":"lex_prime_set",
		"雷克斯P蓝图":"lex_prime_blueprint",
		"雷克斯P枪管":"lex_prime_barrel",
		"雷克斯P枪机":"lex_prime_receiver",

		"雷克斯双枪P":"aklex_prime_set",
		"雷克斯双枪P蓝图":"aklex_prime_blueprint",
		"雷克斯双枪P连接器":"aklex_prime_link",

		"飞扬P":"hikou_prime_set",
		"飞扬P镖袋":"hikou_prime_pouch",
		"飞扬P星镖":"hikou_prime_stars",
		"飞扬P蓝图":"hikou_prime_blueprint",
		
		"野马P":"bronco_prime_set",
		"野马P蓝图":"bronco_prime_blueprint",
		"野马P枪管":"bronco_prime_barrel",
		"野马P枪机":"bronco_prime_receiver",

		"西诺斯P":"cernos_prime_set",
		"西诺斯P蓝图":"cernos_prime_blueprint",
		"西诺斯P上弓臂":"cernos_prime_upper_limb",
		"西诺斯P下弓臂":"cernos_prime_lower_limb",
		"西诺斯P弓身":"cernos_prime_grip",
		"西诺斯P弓弦":"cernos_prime_string",

		"绯红布里斯提卡":"rakta_ballistica",

		"绯红西诺斯":"rakta_cernos",

		"终极螺钉步枪":"telos_boltor",

		"棱晶葛拉卡达":"prisma_grakata",

		"枢议赫利俄光锤":"synoid_heliocor",

		"诡计之刃":"stropha_set",
		"诡计之刃枪托":"stropha_stock",
		"诡计之刃刀刃":"stropha_blade",
		"诡计之刃枪机":"stropha_receiver",
		"诡计之刃枪管":"stahlta_barrel",

		"逐电":"velox_set",
		"逐电枪机":"velox_receiver",
		"逐电枪管":"velox_barrel",

		"棱晶奥比克斯":"prisma_obex",

		"棱晶斩肉双刀":"prisma_dual_cleavers",

		"棱晶空刃":"prisma_skana",

		"终极螺钉拐刃":"telos_boltace",

		"战争之剑握柄":"war_hilt",
		"战争之剑刀刃":"war_blade",

		"冷冻光束步枪破坏者":"glaxion_vandal",

		"猎豹P":"panthera_prime_set",
		"猎豹P蓝图":"panthera_prime_blueprint",
		"猎豹P枪机":"panthera_prime_receiver",
		"猎豹P枪托":"panthera_prime_stock",
		"猎豹P枪管":"panthera_prime_barrel",

		"绯红暗黑匕首":"rakta_dark_dagger",

		"棱晶阴影":"prisma_shade",

		"钢刃步枪":"stahlta_set",
		"钢刃步枪枪托":"stahlta_stock",
		"钢刃步枪枪机":"stahlta_receiver",

		"马谢特砍刀亡魂":"machete_wraith",

		"棱晶真理巨剑":"prisma_veritux",

		"伊格尼斯亡魂蓝图":"ignis_wraith_blueprint",

		"保障潘塔":"secura_penta",

		"勇气海克":"vaykor_hek",

		"圣洁猛虎":"sancti_tigris",

		"枢议重力奇点拟成枪":"synoid_simulor",

		"凯洛斯特P":"karyst_prime_set",
		"凯洛斯特P握柄":"karyst_prime_handle",
		"凯洛斯特P蓝图":"karyst_prime_blueprint",
		"凯洛斯特P刀刃":"karyst_prime_blade",

		"棱晶特拉":"prisma_tetra",

		"保障勒克塔":"secura_lecta",
		
		"勇气恶龙":"vaykor_sydon",

		"侍刃P":"nikana_prime_set",
		"侍刃P蓝图":"nikana_prime_blueprint",
		"侍刃P刀刃":"nikana_prime_blade",
		"侍刃P握柄":"nikana_prime_hilt",

		"凯旋之爪P":"venka_prime_set",
		"凯旋之爪P爪刃":"venka_prime_blades",
		"凯旋之爪P手套":"venka_prime_gauntlet",
		"凯旋之爪P蓝图":"venka_prime_blueprint",

		"分裂斩斧P":"scindo_prime_set",
		"分裂斩斧P蓝图":"scindo_prime_blueprint",
		"分裂斩斧P刀刃":"scindo_prime_blade",
		"分裂斩斧P握柄":"scindo_prime_handle",

		"双短柄战镰P":"dual_kamas_prime_set",
		"双短柄战镰P蓝图":"dual_kamas_prime_blueprint",
		"双短柄战镰P刀刃":"dual_kamas_prime_blade",
		"双短柄战镰P握柄":"dual_kamas_prime_handle",

		"金工火神亡魂":"vulkar_wraith",

		"保障锡斯特双枪":"secura_dual_cestra",

		"勇气玛瑞火枪":"vaykor_marelok",

		"圣洁雷爆信标":"sancti_castanas",

		"枢议咖玛腕甲枪":"synoid_gammacor",

		"棱晶安格斯壮":"prisma_angstrum",

		"量子切割器破坏者":"quanta_vandal",

		"终极螺钉双枪":"telos_akbolto",

		"苦痛德特昂":"mara_detron",

		"蝰蛇亡魂":"viper_wraith",

		"圣洁执法者":"sancti_magistar",

		"普罗沃破坏者":"prova_vandal",

		"棱晶蛇发女妖":"prisma_gorgon",

		"螺钉步枪P":"boltor_prime_set",
		"螺钉步枪P蓝图":"boltor_prime_blueprint",
		"螺钉步枪P枪管":"boltor_prime_barrel",
		"螺钉步枪P枪机":"boltor_prime_receiver",
		"螺钉步枪P枪托":"boltor_prime_stock",

		"猛虎P":"tigris_prime_set",
		"猛虎P蓝图":"tigris_prime_blueprint",
		"猛虎P枪管":"tigris_prime_barrel",
		"猛虎P枪机":"tigris_prime_receiver",
		"猛虎P枪托":"tigris_prime_stock",

		"海波斯库拉对剑P":"nami_skyla_prime_set",
		"海波斯库拉对剑P蓝图":"nami_skyla_prime_blueprint",
		"海波斯库拉对剑P刀刃":"nami_skyla_prime_blade",
		"海波斯库拉对剑P握柄":"nami_skyla_prime_handle",

		"狼牙P":"fang_prime_set",
		"狼牙P刀刃":"fang_prime_blade",
		"狼牙P握柄":"fang_prime_handle",
		"狼牙P蓝图":"fang_prime_blueprint",

		"玻之武杖P":"bo_prime_set",
		"玻之武杖P饰物":"bo_prime_ornament",
		"玻之武杖P握柄":"bo_prime_handle",
		"玻之武杖P蓝图":"bo_prime_blueprint",

		"鲮鲤剑P":"pangolin_prime_set",
		"鲮鲤剑P刀刃":"pangolin_prime_blade",
		"鲮鲤剑P蓝图":"pangolin_prime_blueprint",
		"鲮鲤剑P握柄":"pangolin_prime_handle",
		
		"科林斯P":"corinth_prime_set",
		"科林斯P枪机":"corinth_prime_receiver",
		"科林斯P蓝图":"corinth_prime_blueprint",
		"科林斯P枪托":"corinth_prime_stock",
		"科林斯P枪管":"corinth_prime_barrel",

		"甲龙双拳P":"ankyros_prime_set",
		"甲龙双拳P刀刃":"ankyros_prime_blade",
		"甲龙双拳P拳套":"ankyros_prime_gauntlet",
		"甲龙双拳P蓝图":"ankyros_prime_blueprint",

		"喀婆萨P库狛项圈":"kavasa_prime_kubrow_collar_set",
		"喀婆萨P库狛项圈蓝图":"kavasa_prime_kubrow_collar_blueprint",
		"喀婆萨P库狛项圈项圈扣":"kavasa_prime_buckle",
		"喀婆萨P库狛项圈项圈带":"kavasa_prime_band",

		"科加基P":"kogake_prime_set",
		"科加基P蓝图":"kogake_prime_blueprint",
		"科加基P靴子":"kogake_prime_boot",
		"科加基P拳套":"kogake_prime_gauntlet",

		"达克拉P":"dakra_prime_set",
		"达克拉P握柄":"dakra_prime_handle",
		"达克拉P蓝图":"dakra_prime_blueprint",
		"达克拉P刀刃":"dakra_prime_blade",

		"迦伦提恩P":"galatine_prime_set",
		"迦伦提恩P刀刃":"galatine_prime_blade",
		"迦伦提恩P握柄":"galatine_prime_handle",
		"迦伦提恩P蓝图":"galatine_prime_blueprint",

		"重击巨锤P":"fragor_prime_set",
		"重击巨锤P锤头":"fragor_prime_head",
		"重击巨锤P蓝图":"fragor_prime_blueprint",
		"重击巨锤P握柄":"fragor_prime_handle",

		"伯斯顿P":"burston_prime_set",
		"伯斯顿P蓝图":"burston_prime_blueprint",
		"伯斯顿P枪管":"burston_prime_barrel",
		"伯斯顿P枪机":"burston_prime_receiver",
		"伯斯顿P枪托":"burston_prime_stock",

		"守望者P":"vectis_prime_set",
		"守望者P枪机":"vectis_prime_receiver",
		"守望者P蓝图":"vectis_prime_blueprint",
		"守望者P枪管":"vectis_prime_barrel",
		"守望者P枪托":"vectis_prime_stock",

		"布莱顿P":"braton_prime_set",
		"布莱顿P枪机":"braton_prime_receiver",
		"布莱顿P枪托":"braton_prime_stock",
		"布莱顿P枪管":"braton_prime_barrel",
		"布莱顿P蓝图":"braton_prime_blueprint",

		"帕里斯P":"paris_prime_set",
		"帕里斯P蓝图":"paris_prime_blueprint",
		"帕里斯P上弓臂":"paris_prime_upper_limb",
		"帕里斯P下弓臂":"paris_prime_lower_limb",
		"帕里斯P弓身":"paris_prime_grip",
		"帕里斯P弓弦":"paris_prime_string",

		"席芭莉丝P":"sybaris_prime_set",
		"席芭莉丝P蓝图":"sybaris_prime_blueprint",
		"席芭莉丝P枪管":"sybaris_prime_barrel",
		"席芭莉丝P枪机":"sybaris_prime_receiver",
		"席芭莉丝P枪托":"sybaris_prime_stock",

		"ODONATA P":"odonata_prime_set",
		"ODONATA P蓝图":"odonata_prime_blueprint",
		"ODONATA P机翼":"odonata_prime_wings",
		"ODONATA P外甲":"odonata_prime_harness",
		"ODONATA P系统":"odonata_prime_systems",

		"搬运者P":"carrier_prime_set",
		"搬运者P外壳":"carrier_prime_carapace",
		"搬运者P蓝图":"carrier_prime_blueprint",
		"搬运者P头":"carrier_prime_cerebrum",
		"搬运者P系统":"carrier_prime_systems",

		"蛟龙P":"wyrm_prime_set",
		"蛟龙P外壳":"wyrm_prime_carapace",
		"蛟龙P系统":"wyrm_prime_systems",
		"蛟龙P蓝图":"wyrm_prime_blueprint",
		"蛟龙P头":"wyrm_prime_cerebrum",

		"赫利俄斯P":"helios_prime_set",
		"赫利俄斯P蓝图":"helios_prime_blueprint",
		"赫利俄斯P头":"helios_prime_cerebrum",
		"赫利俄斯P外壳":"helios_prime_carapace",
		"赫利俄斯P系统":"helios_prime_systems",

		"席尔火枪":"zylok",

		"拉特昂P":"latron_prime_set",
		"拉特昂P蓝图":"latron_prime_blueprint",
		"拉特昂P枪管":"latron_prime_barrel",
		"拉特昂P枪机":"latron_prime_receiver",
		"拉特昂P枪托":"latron_prime_stock",

		"月神P":"soma_prime_set",
		"月神P枪托":"soma_prime_stock",
		"月神P枪机":"soma_prime_receiver",
		"月神P枪管":"soma_prime_barrel",
		"月神P蓝图":"soma_prime_blueprint",

		"收割者P":"reaper_prime_set",
		"收割者P蓝图":"reaper_prime_blueprint",
		"收割者P握柄":"reaper_prime_handle",
		"收割者P刀刃":"reaper_prime_blade",

		"狙击特昂破坏者":"snipetron_vandal_set",
		"狙击特昂破坏者蓝图":"snipetron_vandal_blueprint",
		"狙击特昂破坏者枪管":"snipetron_vandal_barrel",
		"狙击特昂破坏者枪机":"snipetron_vandal_receiver",
		"狙击特昂破坏者枪托":"snipetron_vandal_stock",

		"蛇发女妖亡魂":"gorgon_wraith_set",
		"蛇发女妖亡魂枪管":"gorgon_wraith_barrel",
		"蛇发女妖亡魂枪机":"gorgon_wraith_receiver",
		"蛇发女妖亡魂枪托":"gorgon_wraith_stock",
		"蛇发女妖亡魂蓝图":"gorgon_wraith_blueprint",

		"什长双枪":"dual_decurion_set",
		"什长双枪枪管":"decurion_barrel",
		"什长双枪枪机":"decurion_receiver",

		"凯旋将军破坏者":"imperator_vandal_set",
		"凯旋将军破坏者蓝图":"imperator_vandal_blueprint",
		"凯旋将军破坏者枪管":"imperator_vandal_barrel",
		"凯旋将军破坏者枪机":"imperator_vandal_receiver",

		"病囊飞刃":"pathocyst_set",
		"病囊飞刃下皮层":"pathocyst_subcortex",
		"病囊飞刃刀刃":"pathocyst_blade",
		"病囊飞刃蓝图":"pathocyst_blueprint",

		"合成燃气炮":"cyngas_set",
		"合成燃气炮枪管":"cyngas_barrel",
		"合成燃气炮枪机":"cyngas_receiver",
		"合成燃气炮枪托":"cyngas_stock",

		"光谱切割器破坏者":"spectra_vandal_set",
		"光谱切割器破坏者机体":"spectra_vandal_chassis",
		"光谱切割器破坏者枪管":"spectra_vandal_barrel",
		"光谱切割器破坏者握柄":"spectra_vandal_handle",
		"光谱切割器破坏者蓝图":"spectra_vandal_blueprint",

		"舍杜":"shedu_set",
		"舍杜枪管":"shedu_barrel",
		"舍杜机架":"shedu_chassis",
		"舍杜枪机":"shedu_receiver",
		"舍杜握柄":"shedu_handle",

		"巨浪":"fluctus_set",
		"巨浪弓臂":"fluctus_limbs",
		"巨浪枪管":"fluctus_barrel",
		"巨浪枪托":"fluctus_stock",

		"极速电磁步枪":"velocitus_set",
		"极速电磁步枪枪机":"velocitus_receiver",
		"极速电磁步枪枪管":"velocitus_barrel",
		"极速电磁步枪枪托":"velocitus_stock",

		"菲德菈":"phaedra_set",
		"菲德菈枪管":"phaedra_barrel",
		"菲德菈枪机":"phaedra_receiver",
		"菲德菈枪托":"phaedra_stock",

		"黑鸦":"corvas_set",
		"黑鸦枪管":"corvas_barrel",
		"黑鸦枪托":"corvas_stock",
		"黑鸦枪机":"corvas_receiver",

		"双子蝰蛇亡魂":"twin_vipers_wraith_set",
		"双子蝰蛇亡魂枪机":"twin_vipers_wraith_receivers",
		"双子蝰蛇亡魂枪管":"twin_vipers_wraith_barrels",
		"双子蝰蛇亡魂连接器":"twin_vipers_wraith_link",
		"双子蝰蛇亡魂蓝图":"twin_vipers_wraith_blueprint",

		"驯象钩刃":"agkuza_set",
		"驯象钩刃刀刃":"agkuza_blade",
		"驯象钩刃握柄":"agkuza_handle",
		"驯象钩刃护手":"agkuza_guard",

		"奥努里克斯":"onorix_set",
		"奥努里克斯握柄":"onorix_handle",
		"奥努里克斯刀刃":"onorix_blade",

		"卡拉克亡魂":"karak_wraith_set",
		"卡拉克亡魂蓝图":"karak_wraith_blueprint",
		"卡拉克亡魂枪管":"karak_wraith_barrel",
		"卡拉克亡魂枪机":"karak_wraith_receiver",
		"卡拉克亡魂枪托":"karak_wraith_stock",

		"弗拉克斯亡魂":"furax_wraith_set",
		"弗拉克斯亡魂右拳套":"furax_wraith_right_gauntlet",
		"弗拉克斯亡魂左拳套":"furax_wraith_left_gauntlet",
		"弗拉克斯亡魂蓝图":"furax_wraith_blueprint",

		"希芙":"sheev_set",
		"希芙刀刃":"sheev_blade",
		"希芙散热器":"sheev_heatsink",
		"希芙握柄":"sheev_hilt",
		"希芙蓝图":"sheev_blueprint",

		"斯特朗亡魂":"strun_wraith_set",
		"斯特朗亡魂蓝图":"strun_wraith_blueprint",
		"斯特朗亡魂枪管":"strun_wraith_barrel",
		"斯特朗亡魂枪机":"strun_wraith_receiver",
		"斯特朗亡魂枪托":"strun_wraith_stock",

		"尖幡 蓝图":"pennant_blueprint",

		"压制者 蓝图":"quellor_blueprint",

		"半人马":"centaur_set",
		"半人马刀刃":"centaur_blade",
		"半人马盾":"centaur_aegis",
		"半人马握柄":"centaur_handle",

		"死亡使徒":"kaszas_set",
		"死亡使徒刀刃":"kaszas_blade",
		"死亡使徒握柄":"kaszas_handle",

		"拉特昂亡魂":"latron_wraith_set",
		"拉特昂亡魂蓝图":"latron_wraith_blueprint",
		"拉特昂亡魂枪管":"latron_wraith_barrel",
		"拉特昂亡魂枪机":"latron_wraith_receiver",
		"拉特昂亡魂枪托":"latron_wraith_stock",

		"德拉破坏者":"dera_vandal_set",
		"德拉破坏者蓝图":"dera_vandal_blueprint",
		"德拉破坏者枪管":"dera_vandal_barrel",
		"德拉破坏者枪托":"dera_vandal_stock",
		"德拉破坏者枪机":"dera_vandal_receiver",

		"绝路P":"rubico_prime_set",
		"绝路P蓝图":"rubico_prime_blueprint",
		"绝路P枪管":"rubico_prime_barrel",
		"绝路P枪机":"rubico_prime_receiver",
		"绝路P枪托":"rubico_prime_stock",
		
		"技巧之剑P":"destreza_prime_set",
		"技巧之剑P握柄":"destreza_prime_handle",
		"技巧之剑P蓝图":"destreza_prime_blueprint",
		"技巧之剑P刀刃":"destreza_prime_blade",

		"诸葛连弩P":"zhuge_prime_set",
		"诸葛连弩P枪机":"zhuge_prime_receiver",
		"诸葛连弩P蓝图":"zhuge_prime_blueprint",
		"诸葛连弩P枪管":"zhuge_prime_barrel",
		"诸葛连弩P弓弦":"zhuge_prime_string",
		"诸葛连弩P弓身":"zhuge_prime_grip",

		"提佩多P":"tipedo_prime_set",
		"提佩多P蓝图":"tipedo_prime_blueprint",
		"提佩多P握柄":"tipedo_prime_handle",
		"提佩多P饰物":"tipedo_prime_ornament",

		"食人鱼P":"pyrana_prime_set",
		"食人鱼P蓝图":"pyrana_prime_blueprint",
		"食人鱼P枪管":"pyrana_prime_barrel",
		"食人鱼P枪机":"pyrana_prime_receiver",

		"布莱顿破坏者":"braton_vandal_set",
		"布莱顿破坏者枪管":"braton_vandal_barrel",
		"布莱顿破坏者枪机":"braton_vandal_receiver",
		"布莱顿破坏者枪托":"braton_vandal_stock",
		"布莱顿破坏者蓝图":"braton_vandal_blueprint",

		"拉托破坏者":"lato_vandal_set",
		"拉托破坏者枪管":"lato_vandal_barrel",
		"拉托破坏者枪机":"lato_vandal_receiver",
		"拉托破坏者蓝图":"lato_vandal_blueprint",

		"瓦斯托双枪P":"akvasto_prime_set",
		"瓦斯托双枪Prime 蓝图":"akvasto_prime_blueprint",
		"瓦斯托双枪Prime 连接器":"akvasto_prime_link",
		
		"棱晶葛恩火枪":"prisma_grinlok",

		"苏普拉破坏者":"supra_vandal",

		"棱晶双子小精灵":"prisma_twin_gremlins",

		# MOD类
		"致残突击":"maiming_strike",
		"急进猛突":"blood_rush",
		"持久力P":"primed_continuity",
		"瞬时坚毅":"transient_fortitude",
		"生命力":"vitality",
		"手枪增幅":"pistol_amp",
		"激怒":"provoked",
		"霰弹枪增幅":"shotgun_amp",
		"快速切换":"speed_holster",
		"充能反弹":"reflection",
		"二元性状":"duality",
		"霰弹枪弹药搜集者":"shotgun_scavenger",
		"共鸣地震":"resonating_quake",
		"冷静与疯狂":"calm_and_frenzy",
		"伏打电能":"voltaic_strike",
		"光明纯净":"bright_purity",
		"冲击巨力":"collision_force",
		"剧毒灾害":"virulent_scourge",
		"加速":"quickening",
		"复仇真相":"avenging_truth",
		"奋力一掷":"power_throw",
		"奚落守护":"guardian_derision",
		"持续火力":"quickdraw",
		"蚀骨寒霜":"vicious_frost",
		"积存毁坏":"stockpiled_blight",
		"电流震击":"jolt",
		"表演时间":"shotgun_spazz",
		"转轮弹匣":"repeater_clip",
		"迅速抽换":"twitch",
		"通晓霰弹枪":"shotgun_savvy",
		"速射":"snap_shot",
		"酸性弹药":"acid_shells",
		"蓄力装填":"charged_chamber",
		"雷射瞄具":"laser_sight",
		"鹰眼":"eagle_eye",
		"冲击干扰":"disruptor",
		"弹匣增幅":"magazine_warp",
		"弹鼓":"ammo_drum",
		"恒久折磨":"lingering_torment",
		"无尽苦难":"continuous_misery",
		"霰弹扩充":"ammo_stock",
		"致死加速":"fatal_acceleration",
		"膛线":"serration",
		"综观全局":"overview",
		"暴风使者":"stormbringer",
		"机动瞄准":"agile_aim",
		"极限速度":"terminal_velocity",
		"步枪才能":"rifle_aptitude",
		"污染弹匣":"infected_clip",
		"灭亡CORPUS":"bane_of_corpus",
		"灭亡GRINEER":"bane_of_grineer",
		"灭亡INFESTED":"bane_of_infested",
		"灭亡堕落者":"bane_of_corrupted",
		"灵敏扳机":"speed_trigger",
		"燃烧外壳":"incendiary_coat",
		"猎人 战备":"hunter_munitions",
		"私法 热诚":"vigilante_fervor",
		"簧压膛室":"spring_loaded_chamber",
		"精湛快手":"soft_hands",
		"消音器":"hush",
		"瘟疫手枪":"pistol_pestilence",
		"爆发装填":"fast_hands",
		"破裂":"rupture",
		"弹匣置换":"eject_magazine",
		"弹头导引":"seeker",
		"弹头扩散":"barrel_diffusion",
		"强力猛击":"pummel",
		"感染弹匣":"tainted_clip",
		"慑人神速":"stunning_speed",
		"增压弹匣":"pressurized_magazine",
		"手枪弹药转换":"pistol_ammo_mutation",
		"毒素数列":"toxic_sequence",
		"滑行扫射":"strafing_slide",
		"灼痕焦点":"scorch",
		"热磁弹药":"thermagnetic_shells",
		"熵数尖钉":"entropy_spike",
		"猛烈爆发":"fulmination",
		"枪膛":"bore",
		"延烧数列":"sequence_burn",
		"匍匐靶心":"creeping_bullseye",
		"内置炸药":"concealed_explosives",
		"私法 军备":"vigilante_armaments",
		"穿甲伤害":"piercing_hit",
		"乏能迅敏":"anemic_agility",
		"侵蚀毁坏":"eroding_blight",
		"灵快节拍":"deft_tempo",
		"双重连击":"double_tap",
		"搏命反扑":"final_act",
		"最终一击":"final_tap",
		"液压枪膛":"hydraulic_chamber",
		"液压弹药":"hydraulic_gauge",
		"战无不克":"vanquished_prey",
		"松弛枪盖":"loose_hatch",
		"电流长矛":"voltaic_lance",
		"冰风暴":"ice_storm",
		"破片射击":"shrapnel_shot",
		"毁灭堕落者P":"primed_smite_corrupted",
		"毁灭GRINEER P":"primed_smite_grineer",
		"毁灭CORPUS P":"primed_smite_corpus",
		"毁灭INFESTED P":"primed_smite_infested",
		"箭型弹头":"flechette",
		"粉碎器":"shredder",
		"致命一击":"point_strike",
		"触媒连动":"catalyzer_link",
		"锯齿弹链":"sawtooth_clip",
		"雷筒":"blunderbuss",
		"串联弹匣P":"primed_slip_magazine",
		"弱点专精P":"primed_target_cracker",
		"手枪精通P":"primed_pistol_gambit",
		"火焰装填P":"primed_heated_charge",
		"华彩刀剑":"chromatic_blade",
		"角斗士 钳制":"gladiator_vice",
		"目标感应":"targeting_receptor",
		"瞬杀":"swift_deth",
		"精算射击":"calculated_shot",
		"精算蓄能":"calculated_redirection",
		"致命诱惑":"fatal_attraction",
		"重击者":"thumper",
		"电弧线圈":"arc_coil",
		"重定向":"retarget",
		"金属纤维":"steel_fiber",
		"保护":"protect",
		"凶恶终结":"ferocity",
		"反射":"reflect",
		"咬碎":"bite",
		"啃咬压制":"neutralize",
		"重生":"regen",
		"电光脉冲":"electro_pulse",
		"汽化":"vaporize",
		"构造强化":"enhanced_vitality",
		"自爆":"self_destruct",
		"过热射击":"fired_up",
		"加速充能":"accelerated_deflection",
		"宠物治疗套件":"medi_pet_kit",
		"嗅索取物":"retrieve",
		"挖掘":"dig",
		"忠实搭档":"loyal_companion",
		"搜集":"scavenge",
		"猎人 复元":"hunter_recovery",
		"领袖":"pack_leader",
		"长吻":"proboscis",
		"医疗射线":"medi_ray",
		"残余":"spare_parts",
		"人群驱散":"crowd_dispersion",
		"侦察":"investigator",
		"前锋":"striker",
		"吸取":"vacuum",
		"复仇":"revenge",
		"守护者":"guardian",
		"幽灵":"ghost",
		"弹药储转箱":"ammo_case",
		"战士":"warrior",
		"嚎声":"howl",
		"巨大石者":"titanic_rumbler",
		"幸存生灵":"soul_survivor",
		"幽影之护":"shield_of_shadows",
		"急流":"jet_stream",
		"冰封护罩":"chilling_globe",
		"狙击枪弹药搜集者":"sniper_scavenger",
		"步枪弹药搜集者":"rifle_scavenger",
		"手枪弹药搜集者":"pistol_scavenger",
		"电磁脉冲场":"emp_aura",
		"均衡点":"equilibrium",
		"惩戒":"retribution",
		"护盾瓦解":"shield_disruption",
		"预言 协约":"augur_accord",
		"私法 活力":"vigilante_vigor",
		"速度窜升":"speed_drift",
		"全面驱动":"mobilize",
		"冰冷跃动":"ice_spring",
		"剧毒飞腾":"toxic_flight",
		"撕裂翻转":"rending_turn",
		"机动冲撞":"battering_maneuver",
		"火焰行者":"firewalker",
		"翼膜":"patagium",
		"角斗士 灵巧":"gladiator_finesse",
		"恶怨厅":"hall_of_malevolence",
		"感染者阻抗":"infested_impedance",
		"掠夺":"despoil",
		"构造裂缝":"tectonic_fracture",
		"同化":"assimilate",
		"和平挑衅":"peaceful_provocation",
		"圣域爆发":"hallowed_eruption",
		"失衡护盾":"staggering_shield",
		"寒冰之力":"freeze_force",
		"导路龙骸":"guided_effigy",
		"反物质吸收":"antimatter_absorb",
		"庇护烟幕":"smoke_shadow",
		"怨怒报复":"vexing_retaliation",
		"惩击洗礼":"smite_infusion",
		"感染毒雾":"contagion_cloud",
		"抵消虫群":"negation_swarm",
		"晶管屏障":"transistor_shield",
		"连牙追袭":"homing_fang",
		"非晶变压器P":"primed_morphic_transformer",
		"抚慰之风":"pacifying_bolts",
		"加力燃烧":"afterburner",
		"动力转移":"kinetic_diversion",
		"寒流来袭":"cold_snap",
		"系统重划":"system_reroute",
		"终焉风暴":"eleventh_storm",
		"能量力场":"energy_field",
		"非晶变压器":"morphic_transformer",
		"高效传输":"efficient_transferral",
		"卓越防御":"superior_defenses",
		"耐久强化":"enhanced_durability",
		"能量扩散":"energy_amplifier",
		"辅助动力":"auxiliary_power",
		"超越推进":"hyperion_thrusters",
		"氩晶装甲":"argon_plating",
		"纵横双子":"gemini_cross",
		"炙热黄蜂":"burning_wasp",
		"震撼冲拳":"seismic_palm",
		"飓风海怪":"cyclone_kraken",
		"云暴山碎":"shattering_storm",
		"冷面狂怒":"grim_fury",
		"分裂编织":"sundering_weave",
		"巨林冲击":"clashing_forest",
		"破碎之风":"fracturing_wind",
		"撕裂鹤击":"rending_crane",
		"旋压刺针":"spinning_needle",
		"旋风虎击":"swirling_tiger",
		"无明制裁":"blind_justice",
		"最终先驱":"final_harbinger",
		"沉没之爪":"sinking_talon",
		"冷却液外泄":"coolant_leak",
		"动物本能":"animal_instinct",
		"守护光罩":"sanctuary",
		"强化刀片":"tempered_blade",
		"流星撞击":"meteor_crash",
		"星界剖解":"astral_autopsy",
		"星体切砍":"astral_slash",
		"彗星爆发":"comet_blast",
		"熔岩弹膛":"magma_chamber",
		"类星钻体":"quasar_drill",
		"自动扳机":"automatic_trigger",
		"黄道碎裂":"zodiac_shred",
		"填弹加速":"shell_rush",
		"带电枪管":"electrified_barrel",
		"弹药改良":"modified_munitions",
		"恶毒弹匣":"venomous_clip",
		"极地弹仓":"polar_magazine",
		"燃烧弹头":"combustion_rounds",
		"红晶枪管":"rubedo_lined_barrel",
		"扩充弹匣":"magazine_extension",
		"视差瞄具":"parallax_scope",
		"星云钻孔":"nebula_bore",
		"雕斩螳螂":"carving_mantis",
		"钢铁凤凰":"iron_phoenix",
		"赤红狂舞":"crimson_dervish",
		"血色万柳":"bleeding_willow",
		"猎人骨锯":"hunters_bonesaw",
		"电击触点":"shocking_touch",
		"电磁屏障":"electromagnetic_shielding",
		"画龙点睛":"finishing_touch",
		"裂缝打击":"rift_strike",
		"角斗士 威猛":"gladiator_might",
		"狂暴":"fury",
		"超速击杀":"dispatch_overdrive",
		"震波":"seismic_wave",
		"不朽打击":"enduring_strike",
		"压迫点":"pressure_point",
		"弹跳":"rebound",
		"快速收回":"quick_return",
		"斩铁":"true_steel",
		"长时苦难":"enduring_affliction",
		"熔岩冲击":"molten_impact",
		"热病打击":"fever_strike",
		"火神闪击":"vulcan_blitz",
		"败兴虐杀":"buzz_kill",
		"邪恶蓄力":"corrupt_charge",
		"重创":"heavy_trauma",
		"锯刃":"jagged_edge",
		"静电释放":"static_discharge",
		"飞逝熵数":"entropy_flight",
		"一击必杀":"killing_blow",
		"创口溃烂":"weeping_wounds",
		"北风":"north_wind",
		"增幅线圈":"reflex_coil",
		"残酷组合":"relentless_combination",
		"毁灭CORPUS":"smite_corpus",
		"毁灭GRINEER":"smite_grineer",
		"毁灭INFESTED":"smite_infested",
		"毁灭堕落者":"smite_corrupted",
		"未完之刺":"lasting_sting",
		"弱点侦测":"detect_vulnerability",
		"杀伤计数":"body_count",
		"真实惩罚":"true_punishment",
		"果断裁决":"decisive_judgement",
		"正午":"high_noon",
		"残暴浪潮":"brutal_tide",
		"母神悲歌":"gaias_tragedy",
		"毒蛇螺旋":"coiling_viper",
		"狡狐诈面":"vulpine_mask",
		"朱红暴风":"vermillion_storm",
		"狼鱼咬咬":"gnashing_payara",
		"皇家节奏":"tempo_royale",
		"秋风落叶":"tranquil_cleave",
		"积秽骁龙":"defiled_snapdragon",
		"缠旋风切":"stalking_fan",
		"至尊浪人":"sovereign_outcast",
		"蛰刺狂棘":"stinging_thorn",
		"猎鹰俯击":"swooping_falcon",
		"月落乌啼":"crushing_ruin",
		"星界微光":"astral_twilight",
		"恶毒猛禽":"malicious_raptor",
		"碎裂冲击":"shattering_impact",
		"肢解":"organ_shatter",
		"角斗士 猛突":"gladiator_rush",
		"重点防御":"focused_defense",
		"非凡技巧":"melee_prowess",
		"割裂羽翼":"slicing_feathers",
		"刀锋弹舞":"bullet_dance",
		"双蛇牙突":"crossing_snakes",
		"回转尖峰":"twirling_spire",
		"复仇亡灵":"vengeful_revenant",
		"多流抽击":"flailing_branch",
		"天启异象":"four_riders",
		"尖锐之风":"pointed_wind",
		"弧刃回天":"cleaving_whirlwind",
		"微光利爪":"gleaming_talon",
		"格挡":"parry",
		"护盾充能":"shield_charger",
		"搜刮者":"looter",
		"磨锋之爪":"sharpened_claws",
		"生命值连结":"link_health",
		"猛扑":"pounce",
		"狩猎":"hunt",
		"猎人 命令":"hunter_command",
		"猫眼":"cats_eye",
		"释放":"unleashed",
		"牧羊人":"shepherd",
		"脚底抹油":"hit_and_run",
		"封隙量子":"breach_quanta",
		"虚空隐匿":"void_cloak",
		"舰体编铸":"hull_weave",
		"弹药漩涡":"munitions_vortex",
		"超量打击":"hyperstrike",
		"火势抑制":"fire_suppression",
		"碎裂爆破":"shatter_burst",
		"束缚力场":"tether",
		"战斗锻造":"battle_forge",
		"野蛮压制":"savagery",
		"隐秘追踪":"stalk",
		"顽皮":"mischief",
		"侵略领土":"territorial_aggression",
		"危机感知":"sense_danger",
		"庇护":"shelter",
		"急速偏斜":"hastened_deflection",
		"护甲连结":"link_armor",
		"挥击":"swipe",
		"捶击":"maul",
		"猎人 协力":"hunter_synergy",
		"招福":"charm",
		"摆荡钩索":"swing_line",
		"螺钻打击":"auger_strike",
		"致命匿杀":"covert_lethality",
		"狭窄枪膛":"narrow_barrel",
		"猎人 追踪":"hunter_track",
		"电冲弹药":"shell_shock",
		"电压数列":"voltage_sequence",
		"白霜弹头":"rime_rounds",
		"破灭":"ravage",
		"狂暴追猎":"seeking_fury",
		"破碎正义":"shattering_justice",
		"私法 侵犯":"vigilante_offense",
		"私法 补给":"vigilante_supplies",
		"稳定":"stabilizer",
		"穿甲口径":"piercing_caliber",
		"穿透力":"seeking_force",
		"箭矢转换":"arrow_mutation",
		"破裂填装":"breach_loader",
		"簧压猎箭":"spring_loaded_broadhead",
		"熵数爆发":"entropy_burst",
		"烈焰":"blaze",
		"抵消正义":"neutralizing_justice",
		"撕裂":"shred",
		"散射正义":"scattered_justice",
		"机动装填":"tactical_reload",
		"极恶精准":"vile_precision",
		"步枪弹药转换":"rifle_ammo_mutation",
		"烈焰风暴":"firestorm",
		"毒素弹幕":"toxic_barrage",
		"永恒纯净":"lasting_purity",
		"污秽弹药":"tainted_shell",
		"游离双管":"double_barrel_drift",
		"激冷装填":"chilling_reload",
		"灼热光束":"combustion_beam",
		"炼狱轰击":"scattering_inferno",
		"硬质封填":"hardened_casing",
		"SENTIENT解剖刀":"sentient_scalpel",
		"节流降耗":"revo_reducer",
		"充沛射击":"energizing_shot",
		"空中制霸":"aerial_ace",
		"准备就绪":"preparation",
		"铁甲翱翔":"ironclad_flight",
		"补愈射击":"mending_shot",
		"平稳滑步":"controlled_slide",
		"聚精滑翔":"anchored_glide",
		"闭合激效":"breach_adrenaline",
		"超量载弹":"overloader",
		"责难裁决":"tribunal",
		"肉弹发射":"catapult",
		"炽燃劫掠":"blazing_pillage",
		"迷尘丰益":"spellbound_harvest",
		"存亡之战":"last_stand",
		"撕裂装填":"ripload",
		"展翼飓速":"winged_cyclone",
		"极性线圈":"polar_coil",
		"高效火炮":"ordnance_cheap_shot",
		"捕食者":"predator",
		"相位编织":"phasic_weave",
		"超量打击":"hyperstrike",
		"展翼强御":"winged_force",
		"融蚀护壳":"ablative_shell",
		"舰体编铸":"hull_weave",
		"致命机动":"deadly_maneuvers",
		"精准打击":"precision_strike",
		"碎石堆叠":"rubble_heap",
		"狂化震怒":"enraged",
		"显形孢子":"revealing_spores",
		"晕眩弹药":"dizzying_rounds",
		"增生突变":"abundant_mutation",
		"前装光能炮":"forward_artillery",
		"展翼猛攻":"winged_storm",
		"温度控制":"thermatic",
		"散热装置":"heat_sink",
		"极限护盾":"maxima",
		"阳极电池":"anode_cell",
		"离子燃烧":"ion_burn",
		"净化堕落者P":"primed_cleanse_corrupted",
		"超级通量":"hyperflux",
		"坚壁不摧":"bulkhead",
		"截面密度":"section_density",
		"展翼锋刃":"winged_steel",
		"毁灭弹头":"warhead",
		"净化CORPUS P":"primed_cleanse_corpus",
		"巡航速度":"cruising_speed",
		"高效光能炮":"artillery_cheap_shot",
		"炮台速度":"turret_velocity",
		"快速锁定":"quicklock",
		"深度容纳":"deep_hold",
		"弩炮测距":"ballista_measure",
		"锥型推进器":"conic_nozzle",
		"火炮速度":"ordnance_velocity",
		"净化GRINEER P":"primed_cleanse_grineer",
		"净化INFESTED P":"primed_cleanse_infested",
		"氩晶瞄具":"argon_scope",
		"系绳榴弹":"tether_grenades",
		"纳米涂覆":"nano_applicator",
		"缴械纯净":"disarming_purity",
		"低温弹头":"cryo_rounds",
		"充电弹头":"charged_shell",
		"净化CORPUS":"cleanse_corpus",
		"净化GRINEER":"cleanse_grineer",
		"净化INFESTED":"cleanse_infested",
		"净化堕落者":"cleanse_corrupted",
		"传染蔓延":"contagious_spread",
		"凶恶延伸":"sinister_reach",
		"压缩弹药":"shell_compression",
		"地狱火":"hellfire",
		"夜巡燃烧弹":"nightwatch_napalm",
		"寂静炮组":"silent_battery",
		"全面接触":"full_contact",
		"关键延迟":"critical_delay",
		"冰冷疾风":"frigid_blast",
		"凝胶爆破":"adhesive_blast",
		"灭亡堕落者P":"primed_bane_of_corrupted",
		"尖刃弹头":"bladed_rounds",
		"巨人促进剂":"fomorian_accelerant",
		"分裂膛室":"split_chamber",
		"动力回弹":"kinetic_ricochet",
		"卑劣加速":"vile_acceleration",
		"合金钻头":"metal_auger",
		"耗弱链接":"abating_link",
		"脱离速度":"escape_velocity",
		"腐蚀弹幕":"corroding_barrage",
		"蜕化再生":"regenerative_molt",
		"裂隙洪流":"rift_torrent",
		"贪婪吸引":"greedy_pull",
		"避难所":"haven",
		"铁甲冲锋":"ironclad_charge",
		"长时瘫痪":"prolonged_paralysis",
		"静谧无踪":"hushed_invisibility",
		"风起云涌":"rising_storm",
		"高压粉碎":"fracturing_crush",
		"低温弹头 Prime":"primed_cryo_rounds",
		"抵近射击 Prime":"primed_point_blank",
		"续燃":"afterburn",
		"急冻控场":"chilling_grasp",
		"战术上膛":"tactical_pump",
		"追踪齐射":"seeker_volley",
		"战位":"battle_stations",
		"死亡绽放":"death_blossom",
		"反制系统":"countermeasures",
		"列阵归队":"form_up",
		"坚壁不摧":"bulkhead",
		"热流涌动":"flow_burn",
		"粒子冲撞":"particle_ram",
		"侵入停滞":"intruder_stasis",
		"虚空虹洞":"void_hole",
		"小队治愈":"squad_renew",
		"抵近射击":"point_blank",
		"病原弹头":"pathogen_rounds",
		"痉挛":"convulsion",
		"神枪手":"gunslinger",
		"空中侦察":"air_recon",
		"致命动量":"lethal_momentum",
		"迅敏视觉":"spry_sights",
		"火焰装填":"heated_charge",
		"隼目":"hawk_eye",
		"驱逐CORPUS":"expel_corpus",
		"驱逐GRINEER":"expel_grineer",
		"驱逐INFESTED":"expel_infested",
		"驱逐堕落者":"expel_corrupted",
		"黄蜂蛰刺":"hornet_strike",
		"串联弹匣":"slip_magazine",
		"震荡弹头":"concussion_rounds",
		"深层冷冻":"deep_freeze",
		"毁灭扩展":"ruinous_extension",
		"有去无回":"no_return",
		"空尖弹":"hollow_point",
		"纯净之风":"winds_of_purity",
		"结霜侵蚀":"frostbite",
		"致命洪流":"lethal_torrent",
		"致残枪弹":"maim",
		"过激真相":"stinging_truth",
		"重装火力":"magnum_force",
		"预言 探求":"augur_seeker",
		"内置触媒":"embedded_catalyzer",
		"准确射手":"sure_shot",
		"剃刀射击":"razor_shot",
		"反射拔枪":"reflex_draw",
		"定位辅助":"targeting_subsystem",
		"火线电击":"live_wire",
		"分裂飞行":"split_flights",
		"熄扰脉冲":"blackout_pulse",
		"催泪毒雾":"tear_gas",
		"调节跳跃":"tempered_bound",
		"聚焦加速":"focused_acceleration",
		"充量弹容":"full_capacity",
		"红晶枪管P":"primed_rubedo_lined_barrel",
		"蛇发女妖的狂热":"gorgon_frenzy",
		"精准火枪":"grinloked",
		"紧凑步伐":"hastened_steps",
		"冲击预感":"anticipation",
		"精准弹跳":"calculated_spring",
		"彗星弹头":"comet_rounds",
		"溃散射击":"crash_shot",
		"坚忍":"enguard",
		"觅心猎手":"heartseeker",
		"穿刺弹药":"impaler_munitions",
		"绝壁强攻":"impenetrable_offense",
		"埋伏射击":"lie_in_wait",
		"赏金猎人":"bounty_hunter",
		"一剑在手":"sword_alone",
		"充能电幕":"recharge_barrier",
		"蚀能磁触":"sapping_reach",
		"松弛弹匣":"loose_magazine",
		"剃刀弹药":"razor_munitions",
		"咖玛信标":"gamma_beacon",
		"三角信标":"delta_beacon",
		"HELMINTH凶恶终结":"helminth_ferocity",
		"目标入定":"target_fixation",
		"贯彻始终":"follow_through",
		"光谱虹吸":"spectrosiphon",
		"狙击枪弹药转换":"sniper_ammo_mutation",
		"食人鱼噬咬":"biting_piranha",
		"分裂之刃":"dividing_blades",
		"震动之拳":"quaking_hand",
		"能量产生器":"energy_generator",
		"深红飓风":"scarlet_hurricane",
		"凶途恶径":"vicious_approach",
		"重型弹头":"heavy_warhead",
		"幽暗枯竭":"draining_gloom",
		"精准弹药":"precision_munition",
		"卸能打击":"discharge_strike",
		"剑风":"reach",
		"火绫复苏":"ward_recovery",
		"三幂之力":"power_of_three",
		"抗爆覆甲":"anti_flak_plating",
		"信号闪光":"signal_flare",
		"虚伪连结":"deceptive_bond",
		"紧急后果":"emergent_aftermath",
		"复原装甲":"armored_recovery",
		"金属纤维":"metal_fiber",
		"天圣践踏":"celestial_stomp",
		"高射炮击":"flak_shot",
		"动能碰撞":"kinetic_collision",
		"棱彩护卫":"prism_guard",
		"释能放热":"exothermic",
		"精准爆发":"measured_burst",
		"回气再起":"secondary_wind",
		"上升打击":"soaring_strike",
		"骤然正义":"sudden_justice",
		"战术性撤退":"tactical_retreat",
		"三重连击":"triple_tap",
		"再生分流":"vital_systems_bypass",
		"奇异点":"singularity",
		"反重力榴弹":"anti_grav_grenade",
		"牵绳机雷":"whiplash_mine",
		"协议覆盖":"security_override",
		"避难所":"rift_haven",
		"震波驱动器":"shockwave_actuators",
		"献祭之辉":"immolated_radiance",
		"跃浪好手":"adept_surge",
		"分子裂变":"molecular_fission",
		"屠戮换弹":"kill_switch",
		"加载弹容":"loaded_capacity",
		"松弛枪膛":"loose_chamber",
		"闪避装甲":"armored_evade",
		"轰隆石者":"rumbled",
		"液压枪管":"hydraulic_barrel",
		"轻羽箭":"feathered_arrows",
		"定向汇聚":"directed_convergence",
		"盲目射击":"blind_shot",
		"暗影收割":"shadow_harvest",
		"狡诈面貌":"cunning_aspect",
		"银白天灾":"argent_scourge",
		"撕裂之风":"rending_wind",
		"高贵踏频":"noble_cadence",
		"破碎的战争之剑 一套":"broken_war_set",
		"剧毒升腾":"venomous_rise",
		"肾上腺激素":"adrenaline_boost",
		"恐惧屏障":"dread_ward",
		"反转脉冲":"counter_pulse",
		"突击模式":"assault_mode",
		"菌株吸收":"strain_consume",
		"扫描生命体":"scan_lifeforms",
		"菌株热毒":"strain_fever",
		"ARCH-枪械行家":"archgun_ace",
		"祭血锻造":"blood_forge",
		"野火涌流":"balefire_surge",
		"无尽催眠曲":"endless_lullaby",
		"响应风暴":"reactive_storm",
		"SENTIENT坚毅抵御":"sentient_fortitude",
		"扫描物质":"scan_matter",
		"狂怒穿刺":"piercing_fury",
		"崛起之刃":"rising_steel",
		"无电流飞跃":"no_current_leap",
		"天界黄昏":"celestial_nightfall",
		"终末使者":"last_herald",
		"菌株感染":"strain_infection",
		"菌株爆裂":"strain_eruption",
		"盖霜跳马":"rime_vault",
		"纵腾天际":"poppin_vert",
		"Mesa的华尔兹":"mesa’s_waltz",
		"手枪弹药转换P":"primed_pistol_ammo_mutation",
		"反物质地雷":"antimatter_mine",
		"杂技装甲":"armored_acrobatics",
		"治愈之焰":"healing_flame",
		"护盾过载":"shield_overload",
		"狂化冲动":"hysterical_fixation",
		"亵渎清算":"defiled_reckoning",
		"宿命真理":"fateful_truth",
		"净化斩":"purging_slash",
		"霰弹枪弹药转换P":"primed_shotgun_ammo_mutation",
		"痊愈":"recover",
		"复元":"recuperate",
		"残酷打击":"relentless_assault",
		"空中推进":"air_thrusters",
		"践踏":"trample",
		"特斯拉电容":"tesla_bank",
		"加剧反射":"heightened_reflexes",
		"低能耗飞跃":"low_current_leap",
		"探推－挽拉":"push_and_pull",
		"流星弹药":"meteor_munitions",
		"奥米伽信标":"omega_beacon",
		"片刻喘息":"momentary_pause",
		"暗夜追迹者":"night_stalker",
		"净化烈焰":"purifying_flames",
		"能量超载":"overcharged",
		"溢能感应":"overcharge_detectors",
		"杀戮奖励":"prize_kill",
		"护盾速充":"quick_charge",
		"步枪弹药转换P":"primed_rifle_ammo_mutation",
		"狂暴尚武":"martial_fury",
		"幸运射击":"lucky_shot",
		"极限弹容":"maximum_capacity",
		"顶级掠食者":"apex_predator",
		"算计赢家":"calculated_victory",
		"平衡配重":"counterweight",
		"垂死挣扎":"mortal_conduct",
		"爆散消亡":"explosive_demise",
		"撕裂弹头":"ripper_rounds",
		"飞升技巧":"rising_skill",
		"灼热跳跃":"searing_leap",
		"锯齿边缘":"serrated_edges",
		"锯刃弹头":"serrated_rounds",
		"锐利刀刃":"sharpened_blade",
		"撕碎射击":"shred_shot",
		"坚守":"stand_ground",
		"残盾转换":"surplus_diverters",
		"尖锐子弹":"sharpened_bullets",
		"弱点专精":"target_cracker",
		"戏法增幅":"trick_mag",
		"稳定枪手":"steady_hands",
		"手枪精通":"pistol_gambit",
		"永恒苦痛":"perpetual_agony",
		"毁坏微光":"gleaming_blight",
		"失效保险":"failsafe",
		"血易弹药":"blood_for_ammo",
		"血易能量":"blood_for_energy",
		"自动破解":"auto_breach",
		"无迹可寻":"untraceable",
		"血易生命":"blood_for_life",
		"万能钥匙":"master_key",
		"溜之大吉":"runtime",
		"视野之外":"out_of_sight",
		"牵引光束":"tractor_beam",
		"静态力场":"stasis_field",
		"幽灵伏击":"ambush",
		"星辰分裂":"star_divide",
		"重铁雨落":"mafic_rain",
		"原木冲击":"crashing_timber",
		"污染水螅":"tainted_hydra",
		"盘旋鞭笞":"lashing_coil",
		"崩毁浩劫":"crashing_havoc",
		"坚决专注":"resolute_focus",
		"弹链":"ammo_chain",
		"枯竭诅咒":"desiccations_curse",
		"毁坏毒素":"toxic_blight",
		"治愈归复":"healing_return",
		"漂移接触":"drifting_contact",
		"熵数起爆":"entropy_detonation",
		"爆裂刀刃":"volcanic_edge",
		"正义刀锋":"justice_blades",
		"狂战士":"berserker",
		"真相之刃":"blade_of_truth",
		"破甲":"sundering_strike",
		"簧压刀刃":"spring_loaded_blade",
		"聚焦能量":"focus_energy",
		"能量导引":"energy_channel",
		"腐坏打击":"spoiled_strike",
		"生命打击":"life_strike",
		"旋风":"whirlwind",
		"撕裂打击":"rending_strike",
		"异况超量":"condition_overload",
		"消音":"suppress",
		"液压准心":"hydraulic_crosshairs",
		"压迫点P":"primed_pressure_point",
		"热病打击P":"primed_fever_strike",
		"重创P":"primed_heavy_trauma",
		"预言 契约":"augur_pact",
		"剑风P":"primed_reach",
		"地狱弹膛":"hells_chamber",
		"填弹上膛":"lock_and_load",
		"尖牙连射":"fanged_fusillade",
		"加速冲击":"accelerated_blast",
		"灭亡INFESTED P":"primed_bane_of_infested",
		"灭亡GRINEER P":"primed_bane_of_grineer",
		"灭亡CORPUS P":"primed_bane_of_corpus",
		"制导弹药":"guided_ordnance",
		"高压电流":"high_voltage",
		"霰弹枪弹药转换":"shotgun_ammo_mutation",
		"雷火":"thunderbolt",
		"耗竭装填":"depleted_reload",
		"腐败弹匣":"tainted_mag",
		"致命数列":"deadly_sequence",
		"致命火力":"malignant_force",
		"虚弱动能":"frail_momentum",
		"过载弹匣":"burdened_magazine",
		"连续冲击":"crash_course",
		"通量射线步枪超载":"flux_overdrive",
		"重口径":"heavy_caliber",
		"重锤射击":"hammer_shot",
		"野火":"wildfire",
		"铝热焊弹":"thermite_rounds",
		"锁定目标":"target_acquired",
		"镀金真相":"gilded_truth",
		"降速暴击":"critical_deceleration",
		"扫荡锯齿":"sweeping_serration",
		"恶性扩散":"vicious_spread",
		"恒稳枪杆":"gun_glide",
		"弱点感应":"vital_sense",
		"狂怒标枪":"furious_javelin",
		"狂热火球":"fireball_frenzy",
		"猛毒附加":"venom_dose",
		"生命之池":"pool_of_life",
		"电击加速":"shocking_speed",
		"电击奇兵":"shock_trooper",
		"狂化突击":"hysterical_assault",
		"电容":"capacitance",
		"矿石凝视":"ore_gaze",
		"破碎声波":"sonic_fracture",
		"碎铁弹片":"iron_shrapnel",
		"磁吸释放":"magnetized_discharge",
		"神圣清算":"hallowed_reckoning",
		"穿刺抛体":"piercing_navigator",
		"疗愈漩涡":"curative_undertow",
		"爆炸戏法":"explosive_legerdemain",
		"枪口闪焰":"muzzle_flash",
		"欺幻魔灯":"beguiling_lantern",
		"残响共鸣":"resonance",
		"残酷无息":"savage_silence",
		"永恒之护":"everlasting_ward",
		"涌流突进":"surging_dash",
		"混乱领域":"chaos_sphere",
		"渗透":"infiltrate",
		"滞痕冰浪":"ice_wave_impedance",
		"潮汐涌净":"tidal_impunity",
		"火成碎流":"pyroclastic_flow",
		"火绫守护":"safeguard",
		"灾变连连":"cataclysmic_continuum",
		"精神狂怒":"mind_freak",
		"广域之视":"broad_eye",
		"终结闪光":"radiant_finish",
		"缓动惊骇":"creeping_terrify",
		"爆发装填P":"primed_fast_hands",
		"破灭P":"primed_ravage",
		"迅敏动量":"swift_momentum",
		"战斗教条":"combat_discipline",
		"空气动力":"aerodynamic",
		"近战指引":"melee_guidance",
		"牺牲":"sacrifice",
		"深渊之火":"atlantis_vulcan",
		"收割螺旋":"reaping_spiral",
		"能量转化":"energy_inversion",
		"中空子弹":"hollowed_bullets",
		"双重弹头":"dual_rounds",
		"冰冷刃缘":"glacial_edge",
		"剧毒螯刺":"poisonous_sting",
		"炽烈坚刃":"blazing_steel",
		"狂怒":"furor",
		"通电刀刃":"galvanized_blade",
		"切割刃缘":"cutting_edge",
		"炽燃钢铁":"searing_steel",
		"延展":"extend",
		"瞬间冲击":"sudden_impact",
		"血色刃缘":"bleeding_edge",
		"重生P":"primed_regen",
		"护卫传送":"safeguard_switch",
		"弹道靶心":"ballistic_bullseye",
		"原始暴怒":"primal_rage",
		"化像之道":"path_of_statues",
		"削甲手里剑":"seeking_shuriken",
		"永恒战意":"eternal_war",
		"汲能榨取":"vampire_leech",
		"漏斗状云":"funnel_clouds",
		"致命传送":"fatal_teleport",
		"贪夺触角":"pilfering_swarm",
		"践踏加固":"reinforcing_stomp",
		"辐射缴械":"irradiating_disarm",
		"驱逐力场":"repelling_bastille",
		"中子星爆":"neutron_star",
		"元素沙暴":"elemental_sandstorm",
		"全蚀":"total_eclipse",
		"冰冷雪崩":"icy_avalanche",
		"凤凰新生":"phoenix_renewal",
		"刺骨战吼":"piercing_roar",
		"救星诱饵":"savior_decoy",
		"生长怪奇":"peculiar_growth",
		"再启动":"reawaken",
		"抵消":"negate",
		"幼体爆发":"larva_burst",
		"充电弹头P":"primed_charged_shell",
		"治愈玻片":"mending_splinters",
		"指挥家":"conductor",
		"持续火力P":"primed_quickdraw",
		"蓄积长鞭":"accumulating_whipclaw",
		"合成 解构":"synth_deconstruct",
		"合成 纤维":"synth_fiber",
		"合成 充能":"synth_charge",
		"合成 反射":"synth_reflex",
		"机甲 超载":"mecha_overdrive",
		"机甲 充能":"mecha_recharge",
		"强化箭袋":"empowered_quiver",
		"应急备案":"plan_b",
		"不竭贪婪":"insatiable",
		"适应":"adaptation",
		"花开怪奇":"peculiar_bloom",
		"机甲 强化":"mecha_empowered",
		"技法 引力":"tek_gravity",
		"技法 连带":"tek_collateral",
		"机甲 脉冲":"mecha_pulse",
		"技法 猛袭":"tek_assault",
		"技法 强化":"tek_enhance",
		"冲刺提升":"sprint_boost",
		"庇护焚炉":"warding_thurible",
		"分裂槌音":"partitioned_mallet",
		"护盾连结":"link_shields",
		"包覆游云":"enveloping_cloud",
		"集中箭矢":"concentrated_arrow",
		"割魂火圈":"reaping_chakram",
		"能量转移":"energy_transfer",
		"气息疗愈":"odomedic",
		"贪夺穹顶":"pilfering_strangledome",
		"致盲掠夺":"blinding_reave",
		"薇娜丽的护卫":"venari_bodyguard",
		"慧黠斩剃":"wise_razor",
		"牙齿毒液":"venom_teeth",
		"冰冻双颚":"frost_jaw",
		"电击项圈":"shock_collar",
		"狂风猛踢":"gale_kick",
		"反重力阵列":"anti_grav_array",
		"猛爆致病":"teeming_virulence",
		"动物本能P":"primed_animal_instinct",
		"声波提升":"sonic_boost",
		"盗贼大师":"master_thief",
		"顶天立地":"sure_footed",
		"敌人感应":"enemy_sense",
		"川流不息P":"primed_flow",
		"电光冲刺":"lightning_dash",
		"心志偏狭":"narrow_minded",
		"盲怒":"blind_rage",
		"过度延展":"overextended",
		"力量窜升":"power_drift",
		"聚精会神":"intensify",
		"灵活装甲":"armored_agility",
		"痛苦阈值":"pain_threshold",
		"入侵者":"intruder",
		"随机应变":"quick_thinking",
		"不朽意志":"undying_will",
		"猎人 肾上腺素":"hunter_adrenaline",
		"减震器":"shock_absorbers",
		"毒抗":"antitoxin",
		"毒素抵抗":"toxin_resistance",
		"火焰防护":"flame_repellent",
		"反射防御":"reflex_guard",
		"矫捷窜升":"agility_drift",
		"隔热":"insulation",
		"飞行员":"aviator",
		"侦敌雷达":"enemy_radar",
		"匿踪窜升":"stealth_drift",
		"震地冲击":"heavy_impact",
		"不屈不挠":"fortitude",
		"避雷针":"lightning_rod",
		"角斗士 圣盾":"gladiator_aegis",
		"团结一致":"stand_united",
		"预言 通灵":"augur_reach",
		"步枪增幅":"rifle_amp",
		"死亡之眼":"dead_eye",
		"流线外形":"streamlined_form",
		"钢铁充能":"steel_charge",
		"冲刺":"rush",
		"天赋":"natural_talent",
		"狂暴化":"rage",
		"百折不挠":"constitution",
		"翻筋斗":"handspring",
		"快速充能":"fast_deflection",
		"保温服":"warm_coat",
		"强化刀锋":"empowered_blades",
		"成长之力":"growing_power",
		"生命转换":"health_conversion",
		"快速休整":"brief_respite",
		"穿刺步伐":"piercing_step",
		"护盾转移":"transistor_shield",
		"钢铁纤维":"steel_fiber",
		"蓄能重划":"redirection",
		"能量转换":"energy_conversion",
		"持久力":"continuity",
		"预言 启示":"augur_message",
		"弹指瞬技":"fleeting_expertise",
		"简化":"streamline",
		"延伸":"stretch",
		"私法 追踪":"vigilante_pursuit",
		"返老还童":"rejuvenation",
		"体魄":"physique",
		"角斗士 决心":"gladiator_resolve",
		"战利品探测器":"loot_detector",
		"钻石皮肤":"diamond_skin",
		"盗贼天赋":"thiefs_wit",
		"川流不息":"flow",
		"能量虹吸":"energy_siphon",
		"极速复元":"rapid_resilience",
		"活力":"vigor",
		"狡诈窜升":"cunning_drift",
		"磁浮":"maglev",
		"坚忍窜升":"endurance_drift",
		"协力窜升":"coaction_drift",
		"腐蚀投射":"corrosive_projection",
		"预言 神密":"augur_secrets",
		"质子 脉动":"proton_pulse",
		"质子 喷射":"proton_jet",
		"质子 猛扑":"proton_snap",
		"空飞 边际":"aero_periphery",
		"库娃的优雅":"kavats_grace",
		"跃动 信号":"motus_signal",
		"跃动 冲击":"motus_impact",
		"跃动 设局":"motus_setup",
		"空飞 灵巧":"aero_agility",
		"瞬满":"pop_top",
		"护轨器":"rail_guards",
		"膛室P":"primed_chamber",
		"火焰腺体":"flame_gland",
		"空飞 俯瞰":"aero_vantage",
		"膛室P":"primed_chamber",
		"乘空时间":"air_time",
		"轨上燃焰":"trail_blazer",
		"磁吸固锁":"mag_locks",
		"持久誓约":"lasting_covenant",
		"标记目标":"marked_target",
		"关键焦点":"critical_focus",
		"取回":"fetch",
		"致命效率":"deadly_efficiency",
		"高效光束":"efficient_beams",
		"暴露鱼叉":"exposing_harpoon",
		"细心瞄准":"meticulous_aim",
		"领袖P":"primed_pack_leader",
		"覆壳弹药":"sabot_rounds",
		"低温外壳":"hypothermic_shell",
		"带电子弹":"charged_bullets",
		"毒染套管":"contamination_casing",
		"传染性注射":"infectious_injection",
		"冷冻包覆":"cryo_coating",
		"离子注入":"ion_infusion",
		"刀翼闪击":"razorwing_blitz",
		"快速装填":"quick_reload",
		"猛烈发狂":"wild_frenzy",
		"爆发质量":"bursting_mass",
		"凝固汽油榴弹":"napalm_grenades",
		"动能摩擦":"kinetic_friction",
		"启明物悬浮驱动":"venerdo_hoverdrive",
		"惯性减震":"inertia_dampeners",
		"飞光荒疫":"shimmering_blight",
		"驱逐CORPUSP":"primed_expel_corpus",
		"驱逐堕落者P":"primed_expel_corrupted",
		"驱逐GRINEERP":"primed_expel_grineer",
		"驱逐INFESTEDP":"primed_expel_infested",
		"谨慎射击":"cautious_shot",
		"献出力量":"power_donation",
		"斩杀悬浮板":"slay_board",
		"冷抵步":"cold_arrival",
		"狂堆速":"mad_stack",
		"完美平衡":"perfect_balance",
		"翻滚防护":"rolling_guard",
		"强力切换":"vigorous_swap",
		"神射手":"sharpshooter",
		"迅逃夭":"quick_escape",
		"极限加速":"extreme_velocity",
		"氮气喷射":"nitro_boost",
		"收尾痛击":"thrash_landing",

		# 附能类
		"正直 尖刺":"virtuos_spike",
		"正直 熔炉":"virtuos_forge",
		"正直 特洛伊":"virtuos_trojan",
		"和平 电闪":"pax_bolt",
		"和平 电充":"pax_charge",
		"和平 追寻者":"pax_seeker",
		"优雅":"arcane_grace",
		"加速":"arcane_acceleration",
		"神盾":"arcane_aegis",
		"灵敏":"arcane_agility",
		"电阻":"arcane_resistance",
		"速攻":"arcane_strike",
		"通牒":"arcane_ultimatum",
		"神威 凯旋":"exodia_triumph",
		"神威 狩猎":"exodia_hunt",
		"神威 气力":"exodia_force",
		"神威 流行病":"exodia_epidemic",
		"神威 触染":"exodia_contagion",
		"神威 力量":"exodia_might",
		"神威 勇猛":"exodia_valor",
		"神威 勇武":"exodia_brave",
		"魔导 滋养":"magus_nourish",
		"迅速":"arcane_velocity",
		"胜利":"arcane_victory",
		"温暖":"arcane_warmth",
		"魔导 活力":"magus_vigor",
		"正直 空无":"virtuos_None",
		"坦克":"arcane_tanker",
		"枪炮":"arcane_pistoleer",
		"刀刃充能":"arcane_blade_charger",
		"卫士":"arcane_bodyguard",
		"魔导 外壳":"magus_husk",
		"正直 节奏":"virtuos_tempo",
		"正直 狂怒":"virtuos_fury",
		"魔导 游云":"magus_cloud",
		"正直 打击":"virtuos_strike",
		"魔导 韵律":"magus_cadence",
		"正直 鬼魅":"virtuos_ghost",
		"魔导 充盈":"magus_replenish",
		"正直 暗影":"virtuos_shadow",
		"魔导 振奋":"magus_elevate",
		"诡计":"arcane_trickery",
		"正直 突波":"virtuos_surge",
		"和平 高飞":"pax_soar",
		"魔导 超载":"magus_overload",
		"魔导 干扰":"magus_glitch",
		"魔导 复位":"magus_revert",
		"魔导 防火墙":"magus_firewall",
		"魔导 驱动":"magus_drive",
		"魔导 封锁":"magus_lockdown",
		"魔导 穿破":"magus_destruct",
		"魔导 近点":"magus_anomaly",
		"魔导 热熔":"magus_melt",
		"魔导 触媒":"magus_accelerant",
		"魔导 修复":"magus_repair",
		"主武充能":"arcane_primary_charger",
		"节奏":"arcane_tempo",
		"抗毒":"arcane_resistance",
		"结果":"arcane_consequence",
		"偏折":"arcane_deflection",
		"充沛":"arcane_energize",
		"爆发":"arcane_eruption",
		"狂怒":"arcane_fury",
		"保卫者":"arcane_guardian",
		"壁垒":"arcane_barrier",
		"复原":"arcane_healing",
		"动量":"arcane_momentum",
		"消磁":"arcane_Noneifier",
		"幻象":"arcane_phantasm",
		"精确":"arcane_precision",
		"生机":"arcane_pulse",
		"愤怒":"arcane_rage",
		"冰冷":"arcane_ice",
		"觉醒":"arcane_awakening",
		"复仇者":"arcane_avenger",
		"蜘蛛":"arcane_arachne",

		# 紫卡类
		"步枪未开":"rifle_riven_mod_(veiled)",
		"近战未开":"melee_riven_mod_(veiled)",
		"手枪未开":"pistol_riven_mod_(veiled)",
		"ZAW未开":"zaw_riven_mod_(veiled)",
		"组合枪未开":"kitgun_riven_mod_(veiled)",
		"霰弹枪未开":"shotgun_riven_mod_(veiled)",
		"ARCHWING枪械未开":"arch_gun_riven_mod_(veiled)",

		# 物品类
		"传说核心":"legendary_fusion_core",
		"VAY HEK座标频率三角仪":"vay_hek_frequency_triangulator",
	}

	return data

# 翻译到英文（输入的data为字符串类型）
def trans_en(data):
	zh_data=dictionary()
	after_trans=zh_data.get(data)
	if after_trans==None:
		after_trans=data

	return after_trans